CREATE DATABASE myLAB1;

CREATE TABLE users(
  id INT PRIMARY KEY,
  firstname VARCHAR(50),
  lastname VARCHAR(50)
);

ALTER TABLE users ADD COLUMN isadmin INT;
ALTER TABLE users ALTER COLUMN isadmin TYPE BOOLEAN USING isadmin:: BOOLEAN;
ALTER TABLE users ALTER COLUMN isadmin SET DEFAULT FALSE;

CREATE TABLE tasks(
  id SERIAL PRIMARY KEY,
  name VARCHAR(50),
  user_id INT
);


DROP TABLE tasks;
DROP DATABASE myLAB1;